# Imports

In [14]:
import re
from datetime import datetime
from ufsoc import get_sections_from_ufsoc, store_section_ta_to_csv
import pandas as pd
import seaborn as sns
pd.set_option('display.max_columns', 500)
import matplotlib.pyplot as plt

In [15]:
plt.rcParams.update({'font.size': 18})

# Tests

In [ ]:
df = get_sections_from_ufsoc(semester="Fall 2020",
                             course_code="PHY2054",
                             course_title="Physics 2",
                             instructor="Weatherford",
                             department="Physics",
#                             headless=False
                            )
df

# UF Schedule of courses

In [17]:
query_args = dict(
    semester="Spring 2021",
    course_code="PHY2054",
    course_title="Physics 2",
    instructor="Avery",
    department="Physics",
)

input_dir = "~/repos/autocanvas/input/"
store_section_ta_to_csv(input_dir=input_dir, 
                        identifier="phy2054_spring2021", 
                        **query_args)

~/repos/autocanvas/input/section_ta_phy2054_spring2021.csv

,class_number,instuctor_1,instuctor_2,instuctor_3,section_ta_name,lecture_times,meeting_2,meeting_3
0,17631,Shawn Weatherford,Sujata Krishna,Paul Avery,Michael Chung,"T,R | Period 4",T | Period 2,R | Period 2
1,17656,Shawn Weatherford,Sujata Krishna,Paul Avery,Ivan Ishkov,"T,R | Period 4",W | Period 2,F | Period 2
2,17657,Shawn Weatherford,Sujata Krishna,Paul Avery,Michael Chung,"T,R | Period 4",T | Period 5,R | Period 5
3,17658,Shawn Weatherford,Sujata Krishna,Paul Avery,Xiaoliang Zhang,"T,R | Period 4",T | Period 6,R | Period 6
4,17659,Shawn Weatherford,Sujata Krishna,Paul Avery,Ivan Ishkov,"T,R | Period 4",W | Period 3,F | Period 3
5,17660,Shawn Weatherford,Sujata Krishna,Paul Avery,Michael Chung,"T,R | Period 4",T | Period 3,R | Period 3
6,17661,Shawn Weatherford,Sujata Krishna,Paul Avery,Gustavo Perez Sanchez,"T,R | Period 5",W | Period 4,F | Period 4
7,17662,Shawn Weatherford,Sujata Krishna,Paul Avery,Matthew Reinhard,"T,R | Period 5",T | Period 6,R | Period 6
8,17663,Shawn Weatherford,Sujata Krishna,Paul Avery,Gustavo Perez Sanchez,"T,R | Period 5",W | Period 5,F | Period 5
9,17689,Shawn Weatherford,Sujata Krishna,Paul Avery,Matthew Reinhard,"T,R | Period 5",T | Period 8,R | Period 8
10,17690,Shawn Weatherford,Sujata Krishna,Paul Avery,Xiaoliang Zhang,"T,R | Period 5",W | Period 6,F | Period 6
11,17691,Shawn Weatherford,Sujata Krishna,Paul Avery,Gustavo Perez Sanchez,"T,R | Period 5",W | Period 7,F | Period 7
12,17692,Shawn Weatherford,Sujata Krishna,Paul Avery,Ioannis Michaloliakos,"T,R | Period 4",T | Period 8,R | Period 8
13,17694,Shawn Weatherford,Sujata Krishna,Paul Avery,Ioannis Michaloliakos,"T,R | Period 5",T | Period 9,R | Period 9
14,17721,Shawn Weatherford,Sujata Krishna,Paul Avery,Ioannis Michaloliakos,"T,R | Period 5",R | Period 10,T | Period 10
15,17722,Shawn Weatherford,Sujata Krishna,Paul Avery,Christian Bunker,"T,R | Period 5",W | Period 8,F | Period 8
16,17723,Shawn Weatherford,Sujata Krishna,Paul Avery,Christian Bunker,"T,R | Period 4",W | Period 9,F | Period 9
17,17725,Shawn Weatherford,Sujata Krishna,Paul Avery,Ivan Ishkov,"T,R | Period 4",W | Period 5,F | Period 5
18,17726,Shawn Weatherford,Sujata Krishna,Paul Avery,Xiaoliang Zhang,"T,R | Period 4",T | Period 7,R | Period 7
19,17727,Shawn Weatherford,Sujata Krishna,Paul Avery,Matthew Reinhard,"T,R | Period 4",T | Period 5,R | Period 5
20,17728,Shawn Weatherford,Sujata Krishna,Paul Avery,Christian Bunker,"T,R | Period 5",W | Period 10,F | Period 10
21,29863,Shawn Weatherford,Sujata Krishna,Paul Avery,Michael Chung,"T,R | Period 4","T,R | Period 2",NaN
22,29864,Shawn Weatherford,Sujata Krishna,Paul Avery,Ivan Ishkov,"T,R | Period 4","W,F | Period 2",NaN
23,29865,Shawn Weatherford,Sujata Krishna,Paul Avery,Michael Chung,"T,R | Period 4","T,R | Period 5",NaN
24,29866,Shawn Weatherford,Sujata Krishna,Paul Avery,Matthew Reinhard,"T,R | Period 4","T,R | Period 6",NaN
25,29867,Shawn Weatherford,Sujata Krishna,Paul Avery,Ivan Ishkov,"T,R | Period 4","W,F | Period 3",NaN
26,29868,Shawn Weatherford,Sujata Krishna,Paul Avery,Michael Chung,"T,R | Period 4","T,R | Period 3",NaN
27,29869,Shawn Weatherford,Sujata Krishna,Paul Avery,Gustavo Perez Sanchez,"T,R | Period 5","W,F | Period 4",NaN
28,29870,Shawn Weatherford,Sujata Krishna,Paul Avery,Xiaoliang Zhang,"T,R | Period 5","T,R | Period 6",NaN
29,29871,Shawn Weatherford,Sujata Krishna,Paul Avery,Ivan Ishkov,"T,R | Period 5","W,F | Period 5",NaN
30,29872,Shawn Weatherford,Sujata Krishna,Paul Avery,Ioannis Michaloliakos,"T,R | Period 5","T,R | Period 8",NaN
31,29873,Shawn Weatherford,Sujata Krishna,Paul Avery,Xiaoliang Zhang,"T,R | Period 5","W,F | Period 6",NaN
32,29874,Shawn Weatherford,Sujata Krishna,Paul Avery,Gustavo Perez Sanchez,"T,R | Period 5","W,F | Period 7",NaN
33,29875,Shawn Weatherford,Sujata Krishna,Paul Avery,Matthew Reinhard,"T,R | Period 4","T,R | Period 8",NaN
34,29876,Shawn Weatherford,Sujata Krishna,Paul Avery,Ioannis Michaloliakos,"T,R | Period 5","T,R | Period 9",NaN
35,29877,Shawn Weatherford,Sujata Krishna,Paul Avery,Ioannis Michaloliakos,"T,R | Period 5","T,R | Period 10",NaN
36,29878,Shawn Weatherford,Sujata Krishna,Paul Avery,Christian Bunker,"T,R | Period 5","W,F | Period 8",NaN
37,29879,Shawn Weatherford,Sujata Krishna,Paul Avery,Christian Bunker,"T,R | Period 4","W,F | Period 9",NaN
38,29881,Shawn Weatherford,Sujata Krishna,Paul Avery,Gustavo Perez Sanchez,"T,R | Period 4","W,F | Period 5",NaN
39,29882,Shawn Weatherford,Sujata Krishna,Paul Avery,Xiaoliang Zhang,"T,R | Period 4","T,R | Period 7",NaN
40,29883,Shawn Weatherford,Sujata Krishna,Paul Avery,Matthew Reinhard,"T,R | Period 4","T,R | Period 5",NaN
41,29884,Shawn Weatherford,Sujata Krishna,Paul Avery,Christian Bunker,"T,R | Period 5","W,F | Period 10",NaN

In [5]:
# ids = driver.find_elements_by_xpath('//*[@id]')
# for ii in ids:
#     #print ii.tag_name
#     print(ii.get_attribute('id'))